#!/usr/bin/env python3
"""Generate lib/ThaiBrk/ThaiDictData.h from libthai dictionary word lists.

Builds a flat trie over Thai codepoints (offset from U+0E00, so every char
fits one byte) and emits it as a C array. The array is `static constexpr`,
so it lives in flash (rodata, memory-mapped on ESP32) and costs no DRAM.

Node layout (little-endian, byte-addressed):
  uint8_t  flags     bit7 = word may end here, bits 0-6 = edge count (max 127)
  edges[]  4 bytes each: { uint8_t ch, uint24 childOffset }
           sorted by ch for binary search; childOffset is absolute.

Usage:
  python3 scripts/gen_thai_dict.py path/to/libthai/data lib/ThaiBrk/ThaiDictData.h
"""
import glob
import os
import sys


def load_words(data_dir):
    words = set()
    for path in glob.glob(os.path.join(data_dir, "tdict-*.txt")):
        with open(path, encoding="utf-8") as fh:
            for line in fh:
                w = line.strip()
                # Keep pure-Thai words only; the segmenter falls back to
                # cluster rules for anything else.
                if w and all(0x0E01 <= ord(c) <= 0x0E5B for c in w):
                    words.add(w)
    return sorted(words)


class Node:
    __slots__ = ("children", "terminal", "offset")

    def __init__(self):
        self.children = {}
        self.terminal = False
        self.offset = 0


def build_trie(words):
    root = Node()
    for w in words:
        node = root
        for c in w:
            b = ord(c) - 0x0E00
            node = node.children.setdefault(b, Node())
        node.terminal = True
    return root


def serialize(root):
    # Assign offsets breadth-first, then emit.
    order = []
    stack = [root]
    offset = 0
    while stack:
        node = stack.pop()
        node.offset = offset
        offset += 1 + 4 * len(node.children)
        order.append(node)
        for b in sorted(node.children, reverse=True):
            stack.append(node.children[b])
    # The stack ordering above does not guarantee children come after their
    # parent numerically, but offsets are absolute so ordering is irrelevant.
    blob = bytearray(offset)
    for node in order:
        pos = node.offset
        count = len(node.children)
        assert count <= 127, "node fan-out exceeds 7-bit edge count"
        blob[pos] = count | (0x80 if node.terminal else 0)
        pos += 1
        for b in sorted(node.children):
            child = node.children[b]
            assert child.offset < (1 << 24), "trie exceeds 24-bit offsets"
            blob[pos] = b
            blob[pos + 1] = child.offset & 0xFF
            blob[pos + 2] = (child.offset >> 8) & 0xFF
            blob[pos + 3] = (child.offset >> 16) & 0xFF
            pos += 4
    return bytes(blob)


def emit_header(blob, word_count, out_path):
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("// Auto-generated by scripts/gen_thai_dict.py — do not edit.\n")
        fh.write("// Thai word trie built from the libthai project dictionaries\n")
        fh.write("// (https://github.com/tlwg/libthai, LGPL-2.1; word lists used as data).\n")
        fh.write(f"// {word_count} words, {len(blob)} bytes. Flash-resident (constexpr rodata).\n")
        fh.write("#pragma once\n\n#include <cstdint>\n\n")
        fh.write("namespace thaiDict {\n\n")
        fh.write(f"constexpr uint32_t TRIE_SIZE = {len(blob)};\n\n")
        fh.write("constexpr uint8_t TRIE[] = {\n")
        for i in range(0, len(blob), 16):
            chunk = ", ".join(f"0x{b:02X}" for b in blob[i : i + 16])
            fh.write(f"    {chunk},\n")
        fh.write("};\n\n}  // namespace thaiDict\n")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(f"usage: {sys.argv[0]} <libthai-data-dir> <output.h>")
    words = load_words(sys.argv[1])
    blob = serialize(build_trie(words))
    emit_header(blob, len(words), sys.argv[2])
    print(f"{len(words)} words -> {len(blob)} bytes trie -> {sys.argv[2]}")
